In [1]:
from scipy.stats import qmc
import numpy as np
import pandas as pd

from scipy.stats import norm
from scipy.optimize import minimize
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
from sklearn.gaussian_process.kernels import Matern

In [2]:
#Function 5
#Extracting updated data and turning it into a pandas dataframe
data = pd.read_csv('Data/Week 6 - Function 5.csv') 
columns = ['Input 1', 'Input 2','Input 3', 'Input 4','Outputs']
#Remove columns with NaN values
data = data.dropna(axis = 1)
data.columns = columns
#Add Week 7's data to our pandas dataframe
new_data7 = np.array([0.992528, 0.832966, 0.994330, 0.998665,
                     6089.295977690454])
data.loc[len(data)] = new_data7
#Add Week 8's data to our pandas dataframe
new_data8 = np.array([0.970115, 0.990124, 0.944969, 0.988218,
                     6822.940246057326])
data.loc[len(data)] = new_data8
#Add Week 10's data to our pandas dataframe
new_data10 = np.array([0.992917, 0.951906, 0.976171, 0.984828,
                     7013.134740405846])
data.loc[len(data)] = new_data10
#Add Week 11's data to our pandas dataframe
new_data11 = np.array([0.954213, 0.952188, 0.932887, 0.952041,
                     5331.597987100769])
data.loc[len(data)] = new_data11
data

     Input 1   Input 2   Input 3   Input 4      Outputs
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370500
5   0.683432  0.118663  0.829046  0.567577    78.434390
6   0.553621  0.667350  0.323806  0.814870    57.571540
7   0.352356  0.322242  0.116979  0.473113   109.571900
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223600
10  0.677491  0.358510  0.479592  0.072880    24.423090
11  0.583973  0.147243  0.348097  0.428615    64.420150
12  0.306889  0.316878  0.622634  0.095399    63.476720
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806800
15  0.224189  0.846480  0.879484  0.878516  1088.860000
16  0.725262  0.479870  0.088947  0.759760    28.866750
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612800
19  0.126885  0.153430  0.770162  0.190518     9.972332
20  0.204082  0.857143  0.836735  0.857143   862.625800
21  0.244898  0.836735  0.897959  0.897959  1239.189000
22  0.625917  0.905596  0.996631  0.986884  3676.062000
23  0.991058  0.938590  0.996170  0.928593  6279.076000
24  0.996793  0.976752  0.789607  0.935088  4663.265000
25  0.992528  0.832966  0.994330  0.998665  6089.295978
26  0.970115  0.990124  0.944969  0.988218  6822.940246
27  0.992917  0.951906  0.976171  0.984828  7013.134740
28  0.954213  0.952188  0.932887  0.952041  5331.597987

In [4]:
#Extract the Data Into Numpy Arrays
X = np.array(data[['Input 1', 'Input 2', 'Input 3', 'Input 4']])
Y = np.array(data[['Outputs']])

In [66]:
#Using latin hypercube sampling to initialise a set of candidate points in a trust region
#Initialise points in the unit hypercube
d = 4
n = 40000
sampler = qmc.LatinHypercube(d, seed = 42)
grid = sampler.random(n) 

#Scale points generated in the unit hypercube to be inside trust region
#Trust hypercube of radius delta centered at best point with from observed data is 
#[x_best-delta, x_best_plus]
x_best = X[np.argmax(Y)]
#Set radius of hypercube
delta = 0.005
#note that delta is set very low because best point is very close to the boundary of domain
#lower and upper bounds of hypercube

lb = x_best-40*delta 
ub = x_best+delta

#scale points from unit hypercube to be inside trust region
scaled_grid = np.clip(lb + grid * (ub-lb),0,1)

In [67]:
#We now set the Kernel to be the Matern Kernel
nu = 2.5
kernel = Matern(
    length_scale_bounds=(1e-2, 2),
    nu= nu
)
print("Kernel:", kernel)
gp = GaussianProcessRegressor(
    kernel=kernel,
    alpha=1e-10,
    normalize_y = True)
print(gp)
gp.fit(X,Y)

mu, std = gp.predict(scaled_grid, return_std = True)

Kernel: Matern(length_scale=1, nu=2.5)
GaussianProcessRegressor(kernel=Matern(length_scale=1, nu=2.5),
                         normalize_y=True)

In [68]:
#Calculate UCB
beta = 0.2 #set exploration parameter
UCB = mu + beta*std 
#Find point that maximises UCB acquisition function
x_next = scaled_grid[np.argmax(UCB)]
print("Next suggested point:", np.round(x_next,6))

Next suggested point: [0.991791 0.954881 0.96989  0.987413]

In [3]:
#Week 12

#Add new data
new_data = np.array([0.991791, 0.954881, 0.969890, 0.987413,6981.275294969248])
data.loc[len(data)] = new_data
data

     Input 1   Input 2   Input 3   Input 4      Outputs
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370500
5   0.683432  0.118663  0.829046  0.567577    78.434390
6   0.553621  0.667350  0.323806  0.814870    57.571540
7   0.352356  0.322242  0.116979  0.473113   109.571900
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223600
10  0.677491  0.358510  0.479592  0.072880    24.423090
11  0.583973  0.147243  0.348097  0.428615    64.420150
12  0.306889  0.316878  0.622634  0.095399    63.476720
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806800
15  0.224189  0.846480  0.879484  0.878516  1088.860000
16  0.725262  0.479870  0.088947  0.759760    28.866750
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612800
19  0.126885  0.153430  0.770162  0.190518     9.972332
20  0.204082  0.857143  0.836735  0.857143   862.625800
21  0.244898  0.836735  0.897959  0.897959  1239.189000
22  0.625917  0.905596  0.996631  0.986884  3676.062000
23  0.991058  0.938590  0.996170  0.928593  6279.076000
24  0.996793  0.976752  0.789607  0.935088  4663.265000
25  0.992528  0.832966  0.994330  0.998665  6089.295978
26  0.970115  0.990124  0.944969  0.988218  6822.940246
27  0.992917  0.951906  0.976171  0.984828  7013.134740
28  0.954213  0.952188  0.932887  0.952041  5331.597987
29  0.991791  0.954881  0.969890  0.987413  6981.275295

In [4]:
#Extract the Data Into Numpy Arrays
X = np.array(data[['Input 1', 'Input 2', 'Input 3', 'Input 4']])
Y = np.array(data[['Outputs']])

In [9]:
#Using latin hypercube sampling to initialise a set of candidate points in a trust region
#Initialise points in the unit hypercube
d = 4
n = 40001
sampler = qmc.LatinHypercube(d, seed = 42)
grid = sampler.random(n) 

#Scale points generated in the unit hypercube to be inside trust region
#Trust hypercube of radius delta centered at best point with from observed data is 
#[x_best-delta, x_best_plus]
x_best = X[np.argmax(Y)]
#Reduce radius of hypercube by 10% since there was no improvement
delta = 0.005*0.9
#note that delta is set very low because best point is very close to the boundary of domain
#lower and upper bounds of hypercube

lb = x_best-40*delta 
ub = x_best+delta

#scale points from unit hypercube to be inside trust region
scaled_grid = np.clip(lb + grid * (ub-lb),0,1)
print("Center of hypercube:", x_best)
print("Upper bound", ub)
print("lower bound", lb)

Center of hypercube: [0.992917 0.951906 0.976171 0.984828]
Upper bound [0.997417 0.956406 0.980671 0.989328]
lower bound [0.812917 0.771906 0.796171 0.804828]

In [10]:
#We now set the Kernel to be the Matern Kernel
nu = 2.5
kernel = Matern(
    length_scale_bounds=(1e-2, 2),
    nu= nu
)
print("Kernel:", kernel)
gp = GaussianProcessRegressor(
    kernel=kernel,
    alpha=1e-10,
    normalize_y = True)
print(gp)
gp.fit(X,Y)

mu, std = gp.predict(scaled_grid, return_std = True)

Kernel: Matern(length_scale=1, nu=2.5)
GaussianProcessRegressor(kernel=Matern(length_scale=1, nu=2.5),
                         normalize_y=True)

In [11]:
#Calculate UCB
beta = 0.2 #set exploration parameter
UCB = mu + beta*std 
#Find point that maximises UCB acquisition function
x_next = scaled_grid[np.argmax(UCB)]
print("Next suggested point:", np.round(x_next,6))

Next suggested point: [0.99611  0.947533 0.976275 0.986529]

In [4]:
#Week 13

#Add new data
new_data = np.array([0.996110, 0.947533, 0.976275, 0.986529,7032.547252121981])
data.loc[len(data)] = new_data
data

     Input 1   Input 2   Input 3   Input 4      Outputs
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370500
5   0.683432  0.118663  0.829046  0.567577    78.434390
6   0.553621  0.667350  0.323806  0.814870    57.571540
7   0.352356  0.322242  0.116979  0.473113   109.571900
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223600
10  0.677491  0.358510  0.479592  0.072880    24.423090
11  0.583973  0.147243  0.348097  0.428615    64.420150
12  0.306889  0.316878  0.622634  0.095399    63.476720
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806800
15  0.224189  0.846480  0.879484  0.878516  1088.860000
16  0.725262  0.479870  0.088947  0.759760    28.866750
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612800
19  0.126885  0.153430  0.770162  0.190518     9.972332
20  0.204082  0.857143  0.836735  0.857143   862.625800
21  0.244898  0.836735  0.897959  0.897959  1239.189000
22  0.625917  0.905596  0.996631  0.986884  3676.062000
23  0.991058  0.938590  0.996170  0.928593  6279.076000
24  0.996793  0.976752  0.789607  0.935088  4663.265000
25  0.992528  0.832966  0.994330  0.998665  6089.295978
26  0.970115  0.990124  0.944969  0.988218  6822.940246
27  0.992917  0.951906  0.976171  0.984828  7013.134740
28  0.954213  0.952188  0.932887  0.952041  5331.597987
29  0.991791  0.954881  0.969890  0.987413  6981.275295
30  0.996110  0.947533  0.976275  0.986529  7032.547252

In [5]:
#Extract the Data Into Numpy Arrays
X = np.array(data[['Input 1', 'Input 2', 'Input 3', 'Input 4']])
Y = np.array(data[['Outputs']])

In [7]:
#Using latin hypercube sampling to initialise a set of candidate points in a trust region
#Initialise points in the unit hypercube
d = 4
n = 40001
sampler = qmc.LatinHypercube(d, seed = 42)
grid = sampler.random(n) 

#Scale points generated in the unit hypercube to be inside trust region
#Trust hypercube of radius delta centered at best point with from observed data is 
#[x_best-delta, x_best_plus]
x_best = X[np.argmax(Y)]
#Increase radius of hypercube by 10% since there was an improvement
delta = 0.005*0.9*1.1
#note that delta is set very low because best point is very close to the boundary of domain
#lower and upper bounds of hypercube

lb = x_best-40*delta 
ub = x_best+delta

#scale points from unit hypercube to be inside trust region
scaled_grid = np.clip(lb + grid * (ub-lb),0,1)
print("Center of hypercube:", x_best)
print("Upper bound", ub)
print("lower bound", lb)

Center of hypercube: [0.99611  0.947533 0.976275 0.986529]
Upper bound [1.00106  0.952483 0.981225 0.991479]
lower bound [0.79811  0.749533 0.778275 0.788529]

In [10]:
#We now set the Kernel to be the Matern Kernel
nu = 2.5
kernel = Matern(
    length_scale_bounds=(1e-2, 2),
    nu= nu
)
print("Kernel:", kernel)
gp = GaussianProcessRegressor(
    kernel=kernel,
    alpha=1e-10,
    normalize_y = True)
print(gp)
gp.fit(X,Y)

mu, std = gp.predict(scaled_grid, return_std = True)

Kernel: Matern(length_scale=1, nu=2.5)
GaussianProcessRegressor(kernel=Matern(length_scale=1, nu=2.5),
                         normalize_y=True)

In [13]:
#Calculate UCB
beta = 0.2 #set exploration parameter
UCB = mu + beta*std 
#Find point that maximises UCB acquisition function
x_next = scaled_grid[np.argmax(UCB)]
print("Next suggested point:", np.round(x_next,6))

Next suggested point: [0.999623 0.942722 0.976389 0.9884  ]