In [1]:
from scipy.stats import qmc
import numpy as np
import pandas as pd

from scipy.stats import norm
from scipy.optimize import minimize
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
from sklearn.gaussian_process.kernels import Matern

In [2]:
#Function 8
#Extracting updated data and turning it into a pandas dataframe
data = pd.read_csv('Data/Week 6 - Function 8.csv') 
columns = ['Input 1', 'Input 2','Input 3', 'Input 4','Input 5','Input 6','Input 7', 'Input 8', 'Outputs']
#Remove columns with NaN values
data = data.dropna(axis = 1)
data.columns = columns
#Add Week 7's data to our pandas dataframe
new_data7 = np.array([0.006676, 0.142850, 0.014612, 0.008493, 0.013195, 0.029041, 0.146052, 0.709045
                     ,9.384219448563])
data.loc[len(data)] = new_data7
#Add Week 8's data to our pandas dataframe
new_data8 = np.array([0.014396, 0.156572, 0.036172, 0.303020, 0.785780, 0.313016, 0.213195, 0.543895
                     ,9.8997474044235])
data.loc[len(data)] = new_data8
#Add Week 9's data to our pandas dataframe
new_data9 = np.array([0.077029, 0.211423, 0.024938, 0.360429, 0.412992, 0.719907, 0.020932, 0.647577
                     ,9.7301737067941])
data.loc[len(data)] = new_data9
#Add Week 10's data to our pandas dataframe
new_data10 = np.array([0.042445, 0.051647, 0.050686, 0.076565, 0.916977, 0.600690, 0.111062, 0.775604
                     ,9.9235528027939])
data.loc[len(data)] = new_data10
#Add Week 11's data to our pandas dataframe
new_data11 = np.array([0.022224, 0.593235, 0.013522, 0.089016, 0.932122, 0.236391, 0.200148, 0.796551
                     ,9.664943011023901])
data.loc[len(data)] = new_data11
data

,Input 1,Input 2,Input 3,Input 4,Input 5,Input 6,Input 7,Input 8,Outputs
0,0.604994,0.292215,0.908453,0.355506,0.201669,0.575338,0.310311,0.734281,7.398721
1,0.178007,0.566223,0.994862,0.210325,0.320153,0.707909,0.635384,0.107132,7.005227
2,0.009077,0.811626,0.520520,0.075687,0.265112,0.091652,0.592415,0.367320,8.459482
3,0.506028,0.653730,0.363411,0.177981,0.093728,0.197425,0.755827,0.292472,8.284008
4,0.359909,0.249076,0.495997,0.709215,0.114987,0.289207,0.557295,0.593882,8.606117
5,0.778818,0.003419,0.337983,0.519528,0.820907,0.537247,0.551347,0.660032,8.541748
6,0.908649,0.062250,0.238260,0.766604,0.132336,0.990244,0.688068,0.742496,7.327435
7,0.586371,0.880736,0.745021,0.546035,0.009649,0.748992,0.230907,0.097916,7.299872
8,0.761137,0.854672,0.382124,0.337352,0.689708,0.309853,0.631380,0.041956,7.957875
9,0.984933,0.699506,0.998885,0.180148,0.580143,0.231087,0.490827,0.313683,5.592193
10,0.112071,0.437736,0.596599,0.592776,0.226982,0.410105,0.921238,0.674753,7.854541
11,0.791888,0.576191,0.694528,0.283424,0.136755,0.279162,0.842767,0.625328,6.791986
12,0.143550,0.937415,0.232325,0.009043,0.414579,0.409325,0.553779,0.205841,8.976554
13,0.769917,0.458759,0.559000,0.694604,0.503199,0.728346,0.784254,0.663131,7.379083
14,0.056447,0.065956,0.022929,0.038786,0.403935,0.801055,0.488307,0.893085,9.598482
15,0.862437,0.482734,0.281869,0.544102,0.887490,0.382655,0.601902,0.476462,8.159983
16,0.351512,0.590065,0.909436,0.678408,0.212826,0.088460,0.410153,0.195724,7.131624
17,0.735904,0.034612,0.728030,0.147427,0.295743,0.445117,0.975180,0.374340,6.767963
18,0.680294,0.255105,0.862188,0.134396,0.326329,0.287907,0.435010,0.364200,7.433744
19,0.044329,0.013581,0.258198,0.577644,0.051280,0.158563,0.591030,0.077953,9.013075
20,0.778345,0.751146,0.314142,0.902986,0.335382,0.386323,0.748972,0.988755,7.310894
21,0.898887,0.523642,0.876783,0.218696,0.900261,0.282766,0.911078,0.472398,5.841067
22,0.145120,0.119328,0.420888,0.387609,0.155423,0.875172,0.510560,0.728611,9.141639
23,0.338954,0.566932,0.376751,0.098916,0.659452,0.245548,0.762483,0.732153,8.817558
24,0.176150,0.293961,0.975680,0.793936,0.923401,0.030842,0.803255,0.595898,6.451943
25,0.028947,0.028279,0.481372,0.613175,0.672660,0.022113,0.601483,0.524885,8.830745
26,0.192640,0.630677,0.416796,0.490529,0.796086,0.654567,0.276241,0.295518,9.344274
27,0.943185,0.218851,0.721184,0.424597,0.986902,0.535183,0.714743,0.960094,6.887846
28,0.532721,0.833693,0.071399,0.116811,0.730693,0.937376,0.866508,0.127902,8.042213
29,0.447096,0.843953,0.729546,0.639151,0.409287,0.132646,0.035909,0.446838,7.692368
30,0.382225,0.557136,0.853102,0.333796,0.265721,0.480873,0.237647,0.768632,7.923759
31,0.532820,0.862308,0.538267,0.049443,0.719701,0.906706,0.108231,0.525348,8.421759
32,0.394865,0.331802,0.740754,0.697862,0.737404,0.783777,0.254495,0.871146,8.278062
33,0.985945,0.873054,0.070393,0.053587,0.734153,0.520259,0.811040,0.103360,7.113457
34,0.964573,0.973980,0.663753,0.662216,0.673122,0.905238,0.458875,0.560918,6.402588
35,0.472071,0.168203,0.086428,0.452656,0.480619,0.622439,0.928974,0.112536,8.472936
36,0.856007,0.638894,0.326192,0.668503,0.240298,0.210299,0.167546,0.963590,7.977685
37,0.810032,0.635046,0.269548,0.869605,0.661922,0.252259,0.765670,0.890549,7.460872
38,0.796253,0.007037,0.355697,0.487566,0.740520,0.706650,0.992914,0.381734,7.436594
39,0.481245,0.102461,0.219486,0.677322,0.247509,0.244341,0.163825,0.715962,9.183005
40,0.050000,0.050000,0.050000,0.050000,0.430000,0.810000,0.430000,0.810000,9.681040
41,0.093073,0.122300,0.002277,0.001717,0.443789,0.767496,0.444821,0.825434,9.668255
42,0.203369,0.199460,0.055810,0.041080,0.992551,0.048234,0.023335,0.121281,9.639839
43,0.007289,0.216820,0.009932,0.288868,0.735821,0.329805,0.088330,0.978397,9.845527
44,0.138020,0.219998,0.058469,0.960296,0.872403,0.982178,0.040041,0.070507,9.005953
45,0.006676,0.142850,0.014612,0.008493,0.013195,0.029041,0.146052,0.709045,9.384219
46,0.014396,0.156572,0.036172,0.303020,0.785780,0.313016,0.213195,0.543895,9.899747
47,0.077029,0.211423,0.024938,0.360429,0.412992,0.719907,0.020932,0.647577,9.730174
48,0.042445,0.051647,0.050686,0.076565,0.916977,0.600690,0.111062,0.775604,9.923553
49,0.022224,0.593235,0.013522,0.089016,0.932122,0.236391,0.200148,0.796551,9.664943

In [7]:
#Extract the Data Into Numpy Arrays
X = np.array(data[['Input 1', 'Input 2', 'Input 3', 'Input 4', 'Input 5', 'Input 6',
                  'Input 7', 'Input 8']])
Y = np.array(data[['Outputs']])

In [8]:
#Using latin hypercube sampling to initialise a set of candidate points in a trust region
#Initialise points in the unit hypercube
d = 8
n = 900000
sampler = qmc.LatinHypercube(d, seed = 42)
grid = sampler.random(n) 

#Scale points generated in the unit hypercube to be inside trust region
#Trust hypercube of radius delta centered at best point with from observed data is 
#[x_best-delta, x_best_plus]
x_best = X[np.argmax(Y)]
#Set radius of hypercube
delta = 0.2
#lower and upper bounds of hypercube
lb = x_best-delta 
ub = x_best+delta

#scale points from unit hypercube to be inside trust region
scaled_grid = np.clip(lb + grid * (ub-lb),0,1)

In [9]:
#We now set the Kernel to be the Matern Kernel
nu = 2.5
kernel = Matern(
    length_scale_bounds=(1e-2, 2),
    nu= nu
)
print("Kernel:", kernel)
gp = GaussianProcessRegressor(
    kernel=kernel,
    alpha=1e-10,
    normalize_y = True)
print(gp)

gp.fit(X,Y)

mu, std = gp.predict(scaled_grid, return_std = True)

Kernel: Matern(length_scale=1, nu=2.5)
GaussianProcessRegressor(kernel=Matern(length_scale=1, nu=2.5),
                         normalize_y=True)

In [12]:
#Calculate UCB
beta = 0.2 #set exploration parameter
UCB = mu + beta*std 
#Find next point that maximises acquisition function
x_next = scaled_grid[np.argmax(UCB)]
print("Next suggested point:", np.round(x_next,6))

Next suggested point: [0.09192  0.203748 0.09847  0.166686 0.732304 0.51622  0.225742 0.703709]

In [3]:
#Week 12
#Add new data
new_data = np.array([0.091920, 0.203748, 0.098470, 0.166686, 0.732304, 0.516220, 0.225742, 0.703709,9.9887644149959])
data.loc[len(data)] = new_data
data

,Input 1,Input 2,Input 3,Input 4,Input 5,Input 6,Input 7,Input 8,Outputs
0,0.604994,0.292215,0.908453,0.355506,0.201669,0.575338,0.310311,0.734281,7.398721
1,0.178007,0.566223,0.994862,0.210325,0.320153,0.707909,0.635384,0.107132,7.005227
2,0.009077,0.811626,0.520520,0.075687,0.265112,0.091652,0.592415,0.367320,8.459482
3,0.506028,0.653730,0.363411,0.177981,0.093728,0.197425,0.755827,0.292472,8.284008
4,0.359909,0.249076,0.495997,0.709215,0.114987,0.289207,0.557295,0.593882,8.606117
5,0.778818,0.003419,0.337983,0.519528,0.820907,0.537247,0.551347,0.660032,8.541748
6,0.908649,0.062250,0.238260,0.766604,0.132336,0.990244,0.688068,0.742496,7.327435
7,0.586371,0.880736,0.745021,0.546035,0.009649,0.748992,0.230907,0.097916,7.299872
8,0.761137,0.854672,0.382124,0.337352,0.689708,0.309853,0.631380,0.041956,7.957875
9,0.984933,0.699506,0.998885,0.180148,0.580143,0.231087,0.490827,0.313683,5.592193
10,0.112071,0.437736,0.596599,0.592776,0.226982,0.410105,0.921238,0.674753,7.854541
11,0.791888,0.576191,0.694528,0.283424,0.136755,0.279162,0.842767,0.625328,6.791986
12,0.143550,0.937415,0.232325,0.009043,0.414579,0.409325,0.553779,0.205841,8.976554
13,0.769917,0.458759,0.559000,0.694604,0.503199,0.728346,0.784254,0.663131,7.379083
14,0.056447,0.065956,0.022929,0.038786,0.403935,0.801055,0.488307,0.893085,9.598482
15,0.862437,0.482734,0.281869,0.544102,0.887490,0.382655,0.601902,0.476462,8.159983
16,0.351512,0.590065,0.909436,0.678408,0.212826,0.088460,0.410153,0.195724,7.131624
17,0.735904,0.034612,0.728030,0.147427,0.295743,0.445117,0.975180,0.374340,6.767963
18,0.680294,0.255105,0.862188,0.134396,0.326329,0.287907,0.435010,0.364200,7.433744
19,0.044329,0.013581,0.258198,0.577644,0.051280,0.158563,0.591030,0.077953,9.013075
20,0.778345,0.751146,0.314142,0.902986,0.335382,0.386323,0.748972,0.988755,7.310894
21,0.898887,0.523642,0.876783,0.218696,0.900261,0.282766,0.911078,0.472398,5.841067
22,0.145120,0.119328,0.420888,0.387609,0.155423,0.875172,0.510560,0.728611,9.141639
23,0.338954,0.566932,0.376751,0.098916,0.659452,0.245548,0.762483,0.732153,8.817558
24,0.176150,0.293961,0.975680,0.793936,0.923401,0.030842,0.803255,0.595898,6.451943
25,0.028947,0.028279,0.481372,0.613175,0.672660,0.022113,0.601483,0.524885,8.830745
26,0.192640,0.630677,0.416796,0.490529,0.796086,0.654567,0.276241,0.295518,9.344274
27,0.943185,0.218851,0.721184,0.424597,0.986902,0.535183,0.714743,0.960094,6.887846
28,0.532721,0.833693,0.071399,0.116811,0.730693,0.937376,0.866508,0.127902,8.042213
29,0.447096,0.843953,0.729546,0.639151,0.409287,0.132646,0.035909,0.446838,7.692368
30,0.382225,0.557136,0.853102,0.333796,0.265721,0.480873,0.237647,0.768632,7.923759
31,0.532820,0.862308,0.538267,0.049443,0.719701,0.906706,0.108231,0.525348,8.421759
32,0.394865,0.331802,0.740754,0.697862,0.737404,0.783777,0.254495,0.871146,8.278062
33,0.985945,0.873054,0.070393,0.053587,0.734153,0.520259,0.811040,0.103360,7.113457
34,0.964573,0.973980,0.663753,0.662216,0.673122,0.905238,0.458875,0.560918,6.402588
35,0.472071,0.168203,0.086428,0.452656,0.480619,0.622439,0.928974,0.112536,8.472936
36,0.856007,0.638894,0.326192,0.668503,0.240298,0.210299,0.167546,0.963590,7.977685
37,0.810032,0.635046,0.269548,0.869605,0.661922,0.252259,0.765670,0.890549,7.460872
38,0.796253,0.007037,0.355697,0.487566,0.740520,0.706650,0.992914,0.381734,7.436594
39,0.481245,0.102461,0.219486,0.677322,0.247509,0.244341,0.163825,0.715962,9.183005
40,0.050000,0.050000,0.050000,0.050000,0.430000,0.810000,0.430000,0.810000,9.681040
41,0.093073,0.122300,0.002277,0.001717,0.443789,0.767496,0.444821,0.825434,9.668255
42,0.203369,0.199460,0.055810,0.041080,0.992551,0.048234,0.023335,0.121281,9.639839
43,0.007289,0.216820,0.009932,0.288868,0.735821,0.329805,0.088330,0.978397,9.845527
44,0.138020,0.219998,0.058469,0.960296,0.872403,0.982178,0.040041,0.070507,9.005953
45,0.006676,0.142850,0.014612,0.008493,0.013195,0.029041,0.146052,0.709045,9.384219
46,0.014396,0.156572,0.036172,0.303020,0.785780,0.313016,0.213195,0.543895,9.899747
47,0.077029,0.211423,0.024938,0.360429,0.412992,0.719907,0.020932,0.647577,9.730174
48,0.042445,0.051647,0.050686,0.076565,0.916977,0.600690,0.111062,0.775604,9.923553
49,0.022224,0.593235,0.013522,0.089016,0.932122,0.236391,0.200148,0.796551,9.664943
50,0.091920,0.203748,0.098470,0.166686,0.732304,0.516220,0.225742,0.703709,9.988764

In [4]:
#Extract the Data Into Numpy Arrays
X = np.array(data[['Input 1', 'Input 2', 'Input 3', 'Input 4', 'Input 5', 'Input 6',
                  'Input 7', 'Input 8']])
Y = np.array(data[['Outputs']])

In [11]:
#Using latin hypercube sampling to initialise a set of candidate points in a trust region
#Initialise points in the unit hypercube
d = 8
n = 900000
sampler = qmc.LatinHypercube(d, seed = 42)
grid = sampler.random(n) 

#Scale points generated in the unit hypercube to be inside trust region
#Trust hypercube of radius delta centered at best point with from observed data is 
#[x_best-delta, x_best_plus]
x_best = X[np.argmax(Y)]
#Increase radius of hypercube by 10% since there was an improvement
delta = 0.2*1.1
#lower and upper bounds of hypercube
lb = x_best-delta 
ub = x_best+delta

#scale points from unit hypercube to be inside trust region
scaled_grid = np.clip(lb + grid * (ub-lb),0,1)
print("Center of hypercube:", x_best)
print("Upper bound", ub)
print("lower bound", lb)

Center of hypercube: [0.09192  0.203748 0.09847  0.166686 0.732304 0.51622  0.225742 0.703709]
Upper bound [0.31192  0.423748 0.31847  0.386686 0.952304 0.73622  0.445742 0.923709]
lower bound [-0.12808  -0.016252 -0.12153  -0.053314  0.512304  0.29622   0.005742
  0.483709]

In [12]:
#We now set the Kernel to be the Matern Kernel
nu = 2.5
kernel = Matern(
    length_scale_bounds=(1e-2, 2),
    nu= nu
)
print("Kernel:", kernel)
gp = GaussianProcessRegressor(
    kernel=kernel,
    alpha=1e-10,
    normalize_y = True)
print(gp)

gp.fit(X,Y)

mu, std = gp.predict(scaled_grid, return_std = True)

Kernel: Matern(length_scale=1, nu=2.5)
GaussianProcessRegressor(kernel=Matern(length_scale=1, nu=2.5),
                         normalize_y=True)

In [14]:
#Calculate UCB
beta = 0.2 #set exploration parameter
UCB = mu + beta*std 
#Find next point that maximises acquisition function
x_next = scaled_grid[np.argmax(UCB)]
print("Next suggested point:", np.round(x_next,6))

Next suggested point: [0.085097 0.20527  0.149789 0.148856 0.665315 0.515868 0.211622 0.68971 ]

In [4]:
#Week 12
#Add new data
new_data = np.array([0.085097, 0.205270, 0.149789, 0.148856, 0.665315, 0.515868, 0.211622, 0.689710,9.9849281577685])
data.loc[len(data)] = new_data
data

,Input 1,Input 2,Input 3,Input 4,Input 5,Input 6,Input 7,Input 8,Outputs
0,0.604994,0.292215,0.908453,0.355506,0.201669,0.575338,0.310311,0.734281,7.398721
1,0.178007,0.566223,0.994862,0.210325,0.320153,0.707909,0.635384,0.107132,7.005227
2,0.009077,0.811626,0.520520,0.075687,0.265112,0.091652,0.592415,0.367320,8.459482
3,0.506028,0.653730,0.363411,0.177981,0.093728,0.197425,0.755827,0.292472,8.284008
4,0.359909,0.249076,0.495997,0.709215,0.114987,0.289207,0.557295,0.593882,8.606117
5,0.778818,0.003419,0.337983,0.519528,0.820907,0.537247,0.551347,0.660032,8.541748
6,0.908649,0.062250,0.238260,0.766604,0.132336,0.990244,0.688068,0.742496,7.327435
7,0.586371,0.880736,0.745021,0.546035,0.009649,0.748992,0.230907,0.097916,7.299872
8,0.761137,0.854672,0.382124,0.337352,0.689708,0.309853,0.631380,0.041956,7.957875
9,0.984933,0.699506,0.998885,0.180148,0.580143,0.231087,0.490827,0.313683,5.592193
10,0.112071,0.437736,0.596599,0.592776,0.226982,0.410105,0.921238,0.674753,7.854541
11,0.791888,0.576191,0.694528,0.283424,0.136755,0.279162,0.842767,0.625328,6.791986
12,0.143550,0.937415,0.232325,0.009043,0.414579,0.409325,0.553779,0.205841,8.976554
13,0.769917,0.458759,0.559000,0.694604,0.503199,0.728346,0.784254,0.663131,7.379083
14,0.056447,0.065956,0.022929,0.038786,0.403935,0.801055,0.488307,0.893085,9.598482
15,0.862437,0.482734,0.281869,0.544102,0.887490,0.382655,0.601902,0.476462,8.159983
16,0.351512,0.590065,0.909436,0.678408,0.212826,0.088460,0.410153,0.195724,7.131624
17,0.735904,0.034612,0.728030,0.147427,0.295743,0.445117,0.975180,0.374340,6.767963
18,0.680294,0.255105,0.862188,0.134396,0.326329,0.287907,0.435010,0.364200,7.433744
19,0.044329,0.013581,0.258198,0.577644,0.051280,0.158563,0.591030,0.077953,9.013075
20,0.778345,0.751146,0.314142,0.902986,0.335382,0.386323,0.748972,0.988755,7.310894
21,0.898887,0.523642,0.876783,0.218696,0.900261,0.282766,0.911078,0.472398,5.841067
22,0.145120,0.119328,0.420888,0.387609,0.155423,0.875172,0.510560,0.728611,9.141639
23,0.338954,0.566932,0.376751,0.098916,0.659452,0.245548,0.762483,0.732153,8.817558
24,0.176150,0.293961,0.975680,0.793936,0.923401,0.030842,0.803255,0.595898,6.451943
25,0.028947,0.028279,0.481372,0.613175,0.672660,0.022113,0.601483,0.524885,8.830745
26,0.192640,0.630677,0.416796,0.490529,0.796086,0.654567,0.276241,0.295518,9.344274
27,0.943185,0.218851,0.721184,0.424597,0.986902,0.535183,0.714743,0.960094,6.887846
28,0.532721,0.833693,0.071399,0.116811,0.730693,0.937376,0.866508,0.127902,8.042213
29,0.447096,0.843953,0.729546,0.639151,0.409287,0.132646,0.035909,0.446838,7.692368
30,0.382225,0.557136,0.853102,0.333796,0.265721,0.480873,0.237647,0.768632,7.923759
31,0.532820,0.862308,0.538267,0.049443,0.719701,0.906706,0.108231,0.525348,8.421759
32,0.394865,0.331802,0.740754,0.697862,0.737404,0.783777,0.254495,0.871146,8.278062
33,0.985945,0.873054,0.070393,0.053587,0.734153,0.520259,0.811040,0.103360,7.113457
34,0.964573,0.973980,0.663753,0.662216,0.673122,0.905238,0.458875,0.560918,6.402588
35,0.472071,0.168203,0.086428,0.452656,0.480619,0.622439,0.928974,0.112536,8.472936
36,0.856007,0.638894,0.326192,0.668503,0.240298,0.210299,0.167546,0.963590,7.977685
37,0.810032,0.635046,0.269548,0.869605,0.661922,0.252259,0.765670,0.890549,7.460872
38,0.796253,0.007037,0.355697,0.487566,0.740520,0.706650,0.992914,0.381734,7.436594
39,0.481245,0.102461,0.219486,0.677322,0.247509,0.244341,0.163825,0.715962,9.183005
40,0.050000,0.050000,0.050000,0.050000,0.430000,0.810000,0.430000,0.810000,9.681040
41,0.093073,0.122300,0.002277,0.001717,0.443789,0.767496,0.444821,0.825434,9.668255
42,0.203369,0.199460,0.055810,0.041080,0.992551,0.048234,0.023335,0.121281,9.639839
43,0.007289,0.216820,0.009932,0.288868,0.735821,0.329805,0.088330,0.978397,9.845527
44,0.138020,0.219998,0.058469,0.960296,0.872403,0.982178,0.040041,0.070507,9.005953
45,0.006676,0.142850,0.014612,0.008493,0.013195,0.029041,0.146052,0.709045,9.384219
46,0.014396,0.156572,0.036172,0.303020,0.785780,0.313016,0.213195,0.543895,9.899747
47,0.077029,0.211423,0.024938,0.360429,0.412992,0.719907,0.020932,0.647577,9.730174
48,0.042445,0.051647,0.050686,0.076565,0.916977,0.600690,0.111062,0.775604,9.923553
49,0.022224,0.593235,0.013522,0.089016,0.932122,0.236391,0.200148,0.796551,9.664943
50,0.091920,0.203748,0.098470,0.166686,0.732304,0.516220,0.225742,0.703709,9.988764
51,0.085097,0.205270,0.149789,0.148856,0.665315,0.515868,0.211622,0.689710,9.984928

In [5]:
#Extract the Data Into Numpy Arrays
X = np.array(data[['Input 1', 'Input 2', 'Input 3', 'Input 4', 'Input 5', 'Input 6',
                  'Input 7', 'Input 8']])
Y = np.array(data[['Outputs']])

In [7]:
#Using latin hypercube sampling to initialise a set of candidate points in a trust region
#Initialise points in the unit hypercube
d = 8
n = 900000
sampler = qmc.LatinHypercube(d, seed = 42)
grid = sampler.random(n) 

#Scale points generated in the unit hypercube to be inside trust region
#Trust hypercube of radius delta centered at best point with from observed data is 
#[x_best-delta, x_best_plus]
x_best = X[np.argmax(Y)]
#Decrease radius of hypercube by 10% since there was an improvement
delta = 0.2*1.1*0.9
#lower and upper bounds of hypercube
lb = x_best-delta 
ub = x_best+delta

#scale points from unit hypercube to be inside trust region
scaled_grid = np.clip(lb + grid * (ub-lb),0,1)
print("Center of hypercube:", x_best)
print("Upper bound", ub)
print("lower bound", lb)

Center of hypercube: [0.09192  0.203748 0.09847  0.166686 0.732304 0.51622  0.225742 0.703709]
Upper bound [0.28992  0.401748 0.29647  0.364686 0.930304 0.71422  0.423742 0.901709]
lower bound [-0.10608   0.005748 -0.09953  -0.031314  0.534304  0.31822   0.027742
  0.505709]

In [8]:
#We now set the Kernel to be the Matern Kernel
nu = 2.5
kernel = Matern(
    length_scale_bounds=(1e-2, 2),
    nu= nu
)
print("Kernel:", kernel)
gp = GaussianProcessRegressor(
    kernel=kernel,
    alpha=1e-10,
    normalize_y = True)
print(gp)

gp.fit(X,Y)

mu, std = gp.predict(scaled_grid, return_std = True)

Kernel: Matern(length_scale=1, nu=2.5)
GaussianProcessRegressor(kernel=Matern(length_scale=1, nu=2.5),
                         normalize_y=True)

In [9]:
#Calculate UCB
beta = 0.2 #set exploration parameter
UCB = mu + beta*std 
#Find next point that maximises acquisition function
x_next = scaled_grid[np.argmax(UCB)]
print("Next suggested point:", np.round(x_next,6))

Next suggested point: [0.091143 0.246147 0.118623 0.14505  0.699832 0.503704 0.187565 0.678935]