In [1]:
from scipy.stats import qmc
import numpy as np
import pandas as pd

from scipy.stats import norm
from scipy.optimize import minimize
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
from sklearn.gaussian_process.kernels import Matern

In [2]:
#Function 7
#Extracting updated data and turning it into a pandas dataframe
data = pd.read_csv('Data/Week 6 - Function 7.csv') 
columns = ['Input 1', 'Input 2','Input 3', 'Input 4','Input 5','Input 6', 'Outputs']
#Remove columns with NaN values
data = data.dropna(axis = 1)
data.columns = columns
#Add Week 7's data to our pandas dataframe
new_data7 = np.array([0.004636, 0.207768, 0.404112, 0.351555, 0.401196, 0.792288,
                     2.0203487535312235])
data.loc[len(data)] = new_data7
#Add Week 8's data to our pandas dataframe
new_data8 = np.array([0.026756, 0.059727, 0.449213, 0.390822, 0.344762, 0.772857,
                     2.246426597825821])
data.loc[len(data)] = new_data8
data
#Add Week 9's data to our pandas dataframe
new_data9 = np.array([0.000814, 0.012686, 0.415064, 0.520644, 0.332606, 0.845142,
                     1.148647288259179])
data.loc[len(data)] = new_data9
#Add Week 10's data to our pandas dataframe
new_data10 = np.array([0.062188, 0.108207, 0.564947, 0.226737, 0.344570, 0.751893,
                     2.703020381612213])
data.loc[len(data)] = new_data10
#Add Week 11's data to our pandas dataframe
new_data11 = np.array([0.035266, 0.121550, 0.615270, 0.250095, 0.467840, 0.732755,
                     1.9327503892587292])
data.loc[len(data)] = new_data11

data

     Input 1   Input 2   Input 3   Input 4   Input 5   Input 6   Outputs
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411
30  0.090909  0.454545  0.272727  0.181818  0.454545  0.727273  1.299110
31  0.106216  0.471693  0.263253  0.197911  0.432941  0.768419  1.332889
32  0.042879  0.139509  0.201279  0.167391  0.243584  0.957024  1.078252
33  0.002618  0.644617  0.532991  0.053995  0.337592  0.940857  0.508863
34  0.033065  0.543236  0.049355  0.030671  0.305183  0.708242  0.665951
35  0.004636  0.207768  0.404112  0.351555  0.401196  0.792288  2.020349
36  0.026756  0.059727  0.449213  0.390822  0.344762  0.772857  2.246427
37  0.000814  0.012686  0.415064  0.520644  0.332606  0.845142  1.148647
38  0.062188  0.108207  0.564947  0.226737  0.344570  0.751893  2.703020
39  0.035266  0.121550  0.615270  0.250095  0.467840  0.732755  1.932750

In [5]:
#Extract the Data Into Numpy Arrays
X = np.array(data[['Input 1', 'Input 2', 'Input 3', 'Input 4', 'Input 5', 'Input 6']])
Y = np.array(data[['Outputs']])

In [6]:
#Using latin hypercube sampling to initialise a set of candidate points in a trust region
#Initialise points in the unit hypercube
d = 6
n = 300000
sampler = qmc.LatinHypercube(d, seed = 42)
grid = sampler.random(n) 

#Scale points generated in the unit hypercube to be inside trust region
#Trust hypercube of radius delta centered at best point with from observed data is 
#[x_best-delta, x_best_plus]
x_best = X[np.argmax(Y)]
#Set radius of hypercube
delta = 0.2
#lower and upper bounds of hypercube
lb = x_best-delta 
ub = x_best+delta

#scale points from unit hypercube to be inside trust region
scaled_grid = np.clip(lb + grid * (ub-lb),0,1)

In [7]:
#We now set the Kernel to be the Matern Kernel
nu = 2.5
kernel = Matern(
    length_scale_bounds=(1e-2, 2),
    nu= nu
)
print("Kernel:", kernel)
gp = GaussianProcessRegressor(
    kernel=kernel,
    alpha=1e-10,
    normalize_y = True)
print(gp)

gp.fit(X,Y)

mu, std = gp.predict(scaled_grid, return_std = True)

Kernel: Matern(length_scale=1, nu=2.5)
GaussianProcessRegressor(kernel=Matern(length_scale=1, nu=2.5),
                         normalize_y=True)

In [8]:
#Calculate UCB
beta = 0.2 #set exploration parameter
UCB = mu + beta*std 
#Find point that maximises UCB acquistion function
x_next = scaled_grid[np.argmax(UCB)]
print("Next suggested point:", np.round(x_next,6))

Next suggested point: [0.06534  0.093914 0.531454 0.218916 0.324817 0.750458]

In [3]:
#Week 12
#Add new data
new_data = np.array([0.065340, 0.093914, 0.531454, 0.218916, 0.324817, 0.750458,2.75433324433888])
data.loc[len(data)] = new_data
data

     Input 1   Input 2   Input 3   Input 4   Input 5   Input 6   Outputs
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411
30  0.090909  0.454545  0.272727  0.181818  0.454545  0.727273  1.299110
31  0.106216  0.471693  0.263253  0.197911  0.432941  0.768419  1.332889
32  0.042879  0.139509  0.201279  0.167391  0.243584  0.957024  1.078252
33  0.002618  0.644617  0.532991  0.053995  0.337592  0.940857  0.508863
34  0.033065  0.543236  0.049355  0.030671  0.305183  0.708242  0.665951
35  0.004636  0.207768  0.404112  0.351555  0.401196  0.792288  2.020349
36  0.026756  0.059727  0.449213  0.390822  0.344762  0.772857  2.246427
37  0.000814  0.012686  0.415064  0.520644  0.332606  0.845142  1.148647
38  0.062188  0.108207  0.564947  0.226737  0.344570  0.751893  2.703020
39  0.035266  0.121550  0.615270  0.250095  0.467840  0.732755  1.932750
40  0.065340  0.093914  0.531454  0.218916  0.324817  0.750458  2.754333

In [4]:
#Extract the Data Into Numpy Arrays
X = np.array(data[['Input 1', 'Input 2', 'Input 3', 'Input 4', 'Input 5', 'Input 6']])
Y = np.array(data[['Outputs']])

In [15]:
#Using latin hypercube sampling to initialise a set of candidate points in a trust region
#Initialise points in the unit hypercube
d = 6
n = 300000
sampler = qmc.LatinHypercube(d, seed = 42)
grid = sampler.random(n) 

#Scale points generated in the unit hypercube to be inside trust region
#Trust hypercube of radius delta centered at best point with from observed data is 
#[x_best-delta, x_best_plus]
x_best = X[np.argmax(Y)]
#Increase radius of hypercube by 10% since there was an improvement 
delta = 0.2*1.1
#lower and upper bounds of hypercube
lb = x_best-delta 
ub = x_best+delta

#scale points from unit hypercube to be inside trust region
scaled_grid = np.clip(lb + grid * (ub-lb),0,1)
print("Center of hypercube:", x_best)
print("Upper bound", ub)
print("lower bound", lb)

Center of hypercube: [0.06534  0.093914 0.531454 0.218916 0.324817 0.750458]
Upper bound [0.28534  0.313914 0.751454 0.438916 0.544817 0.970458]
lower bound [-0.15466  -0.126086  0.311454 -0.001084  0.104817  0.530458]

In [16]:
#We now set the Kernel to be the Matern Kernel
nu = 2.5
kernel = Matern(
    length_scale_bounds=(1e-2, 2),
    nu= nu
)
print("Kernel:", kernel)
gp = GaussianProcessRegressor(
    kernel=kernel,
    alpha=1e-10,
    normalize_y = True)
print(gp)

gp.fit(X,Y)

mu, std = gp.predict(scaled_grid, return_std = True)

Kernel: Matern(length_scale=1, nu=2.5)
GaussianProcessRegressor(kernel=Matern(length_scale=1, nu=2.5),
                         normalize_y=True)

In [17]:
#Calculate UCB
beta = 0.2 #set exploration parameter
UCB = mu + beta*std 
#Find point that maximises UCB acquistion function
x_next = scaled_grid[np.argmax(UCB)]
print("Next suggested point:", np.round(x_next,6))

Next suggested point: [0.082598 0.089188 0.523786 0.246924 0.294486 0.78208 ]

In [4]:
#Week 13
#Add new data
new_data = np.array([0.082598, 0.089188, 0.523786, 0.246924, 0.294486, 0.782080,2.7017548763419312])
data.loc[len(data)] = new_data
data

     Input 1   Input 2   Input 3   Input 4   Input 5   Input 6   Outputs
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411
30  0.090909  0.454545  0.272727  0.181818  0.454545  0.727273  1.299110
31  0.106216  0.471693  0.263253  0.197911  0.432941  0.768419  1.332889
32  0.042879  0.139509  0.201279  0.167391  0.243584  0.957024  1.078252
33  0.002618  0.644617  0.532991  0.053995  0.337592  0.940857  0.508863
34  0.033065  0.543236  0.049355  0.030671  0.305183  0.708242  0.665951
35  0.004636  0.207768  0.404112  0.351555  0.401196  0.792288  2.020349
36  0.026756  0.059727  0.449213  0.390822  0.344762  0.772857  2.246427
37  0.000814  0.012686  0.415064  0.520644  0.332606  0.845142  1.148647
38  0.062188  0.108207  0.564947  0.226737  0.344570  0.751893  2.703020
39  0.035266  0.121550  0.615270  0.250095  0.467840  0.732755  1.932750
40  0.065340  0.093914  0.531454  0.218916  0.324817  0.750458  2.754333
41  0.082598  0.089188  0.523786  0.246924  0.294486  0.782080  2.701755

In [5]:
#Extract the Data Into Numpy Arrays
X = np.array(data[['Input 1', 'Input 2', 'Input 3', 'Input 4', 'Input 5', 'Input 6']])
Y = np.array(data[['Outputs']])

In [7]:
#Using latin hypercube sampling to initialise a set of candidate points in a trust region
#Initialise points in the unit hypercube
d = 6
n = 300000
sampler = qmc.LatinHypercube(d, seed = 42)
grid = sampler.random(n) 

#Scale points generated in the unit hypercube to be inside trust region
#Trust hypercube of radius delta centered at best point with from observed data is 
#[x_best-delta, x_best_plus]
x_best = X[np.argmax(Y)]
#Decrease radius of hypercube by 10% since there was an improvement 
delta = 0.2*1.1*0.9
#lower and upper bounds of hypercube
lb = x_best-delta 
ub = x_best+delta

#scale points from unit hypercube to be inside trust region
scaled_grid = np.clip(lb + grid * (ub-lb),0,1)
print("Center of hypercube:", x_best)
print("Upper bound", ub)
print("lower bound", lb)

Center of hypercube: [0.06534  0.093914 0.531454 0.218916 0.324817 0.750458]
Upper bound [0.26334  0.291914 0.729454 0.416916 0.522817 0.948458]
lower bound [-0.13266  -0.104086  0.333454  0.020916  0.126817  0.552458]

In [8]:
#We now set the Kernel to be the Matern Kernel
nu = 2.5
kernel = Matern(
    length_scale_bounds=(1e-2, 2),
    nu= nu
)
print("Kernel:", kernel)
gp = GaussianProcessRegressor(
    kernel=kernel,
    alpha=1e-10,
    normalize_y = True)
print(gp)

gp.fit(X,Y)

mu, std = gp.predict(scaled_grid, return_std = True)

Kernel: Matern(length_scale=1, nu=2.5)
GaussianProcessRegressor(kernel=Matern(length_scale=1, nu=2.5),
                         normalize_y=True)

In [9]:
#Calculate UCB
beta = 0.2 #set exploration parameter
UCB = mu + beta*std 
#Find point that maximises UCB acquistion function
x_next = scaled_grid[np.argmax(UCB)]
print("Next suggested point:", np.round(x_next,6))

Next suggested point: [0.006896 0.112535 0.514766 0.241549 0.287126 0.726221]